@echo off
echo Starting Split App Backend...
echo.
echo Building the application...
call mvnw.cmd clean install -DskipTests
echo.
echo Starting the Spring Boot application...
call mvnw.cmd spring-boot:run